version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: "/code-build/docker-credentials/username"
    DOCKER_REGISTRY_PASSWORD: "/code-build/docker-credentials/password"
    DOCKER_REGISTRY_URL: "/code-build/docker-credentials/url"
        
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r aws-ci/simple-python-app/requirements.txt
  build:
    commands:
      - cd aws-ci/simple-python-app/
      - echo "Building Docker Image"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/aws-code-build-python-flask:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/aws-code-build-python-flask:latest"
  post_build:
    commands:
      - echo "Build is Successful"
